---

## ðŸš€ CI/CD - Automation with GitHub Actions

- Sync notebooks from Azure Databricks to GitHub repository
- Automatically commit and push changes when notebooks are updated
- Can be extended to automatically trigger the ADF pipeline

---

## ðŸ” Secrets & Configuration

### 1. GitHub Repository Secrets

Add the following secrets to your GitHub repository:

| Variable Name         | Description                                |
|-----------------------|--------------------------------------------|
| `DATABRICKS_HOST`     | Your Databricks workspace URL              |
| `DATABRICKS_TOKEN`    | Access token for your Databricks           |
| `AZURE_CREDENTIALS`   | JSON format of your Azure Service Principal|
| `SUBSCRIPTION_ID`     | Your Azure Subscription ID                 |
| `RESOURCE_GROUP`      | Your Azure Resource Group name             |

> Format for `AZURE_CREDENTIALS`:
```json
{
  "clientId": "...",
  "clientSecret": "...",
  "tenantId": "...",
  "subscriptionId": "..."
}
