name: Deploy Azure Data Factory

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ADF ARM Template
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          template: demopipelinetu99/ARMTemplateForFactory.json
          parameters: demopipelinetu99/ARMTemplateParametersForFactory.json
          deploymentName: adf-deployer
